"""add author,comment models

Revision ID: 0e59eeccc68b
Revises: 8ae83bc737a8
Create Date: 2022-05-15 23:00:49.696315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e59eeccc68b'
down_revision = '8ae83bc737a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id_comment', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id_comment'], ['blog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('author', 'title')
    op.add_column('users', sa.Column('comments', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'comments')
    op.add_column('author', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('comments')
    # ### end Alembic commands ###
