"""fix bugs

Revision ID: 90089f7961b9
Revises: a46df5c1ba32
Create Date: 2022-05-16 11:44:02.101180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90089f7961b9'
down_revision = 'a46df5c1ba32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('profile_url', sa.String(), nullable=True))
    op.drop_column('author', 'profile_pic_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('profile_pic_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('author', 'profile_url')
    # ### end Alembic commands ###
