"""add roles model

Revision ID: a46df5c1ba32
Revises: 2c95e54b0692
Create Date: 2022-05-16 01:28:02.476309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46df5c1ba32'
down_revision = '2c95e54b0692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('author', sa.Column('profile_pic_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'profile_pic_url')
    op.drop_column('author', 'bio')
    # ### end Alembic commands ###
